export type { BadgeTone } from "./core/badge";
export {
  constrainViewport,
  type OverlayPlacement,
  type OverlayViewport,
  resolveViewport,
  VIEWPORT_PRESETS,
  type ViewportInput,
  type ViewportPreset,
} from "./core/geometry";
export {
  type GuestPhase,
  INITIAL_OVERLAY_STATE,
  type OverlayEvent,
  type OverlayPhase,
  type OverlayState,
  transitionOverlay,
} from "./core/lifecycle";
export {
  type ContentFitFootprint,
  type FixedFootprint,
  isPresentationSnapshot,
  type OverlayPresentation,
  type PreferredPresentationSize,
  type PresentationAuthority,
  type PresentationConstraint,
  type PresentationFootprint,
  type PresentationSize,
  type PresentationSnapshot,
  type PresentationSnapshotInput,
  type PresentationViewport,
  preferredPresentationSize,
  type ResizableFootprint,
  type ResponsivePresentationViewport,
  resolvePresentationSnapshot,
  type VirtualPresentationViewport,
  validatePresentation,
} from "./core/presentation";
export {
  type BridgeEnvelope,
  bridgeEnvelope,
  isBridgeEnvelope,
  WIDGET_SHELL_PROTOCOL,
} from "./core/protocol";
export {
  constrainGeometry,
  DEFAULT_GEOMETRY_LIMITS,
  DEFAULT_RESPONSIVE_BREAKPOINTS,
  type GeometryLimits,
  type HostSize,
  initialGeometry,
  isWindowGeometry,
  moveGeometry,
  type OverlayMode,
  type ResizeCorner,
  type ResponsiveBreakpoints,
  resizeAnchoredGeometry,
  resizeGeometry,
  resizeGeometryFromCorner,
  responsiveMode,
  snapGeometry,
  type WindowGeometry,
} from "./core/window-geometry";
